version: "3"

networks:
  issue-board-test:

services:

  ui:
    container_name: "issue-board-ui-test"
    build:
      context: "./ui"
      dockerfile: "Dockerfile.test"
    command: "npm run test"
    networks:
      - "issue-board-test"
    volumes:
      - "./ui:/app"
      - "/app/node_modules"