version: "3"

networks:
  issue-board-dev:

services:

  postgres:
    container_name: "issue-board-postgres"
    image: "postgres:12.2"
    env_file:
      - "server/.env.dev"
    ports:
      - "5432:5432"
    networks:
      - "issue-board-dev"

  adminer:
    image: "adminer"
    ports:
      - "8080:8080"
    networks:
      - "issue-board-dev"

  server:
    container_name: "issue-board-server"
    build:
      context: "./server"
      dockerfile: "Dockerfile.dev"
    command: "npm run start:dev"
    env_file:
      - "server/.env.dev"
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    ports:
      - "3001:3000"
    networks:
      - "issue-board-dev"

  ui:
    container_name: "issue-board-ui"
    build:
      context: "./ui"
      dockerfile: "Dockerfile.dev"
    command: "npm run start"
    stdin_open: true
    volumes:
      - "./ui:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    networks:
      - "issue-board-dev"
