version: "3"

networks:
  issue-board-prod:

services:

  postgres:
    container_name: "issue-board-postgres-prod"
    image: "postgres:12.2"
    env_file:
      - "./server/.env.prod"
    networks:
      - "issue-board-prod"

  server:
    container_name: "issue-board-server-prod"
    build:
      dockerfile: "Dockerfile.prod"
      context: "./server"
    env_file:
      - "./server/.env.prod"
    networks:
      - "issue-board-prod"

  proxy:
    container_name: "issue-board-proxy-prod"
    build:
      dockerfile: "./proxy/Dockerfile.prod"
      context: "."
    ports:
      - "3000:80"
    networks:
      - "issue-board-prod"