version: "3"

services:

  postgres:
    container_name: "issues-dashboard-postgres"
    image: "postgres:12.2"
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  adminer:
    image: "adminer"
    ports:
      - "8080:8080"

  server:
    container_name: "issues-dashboard-server"
    working_dir: "/app"
    image: "node:12-alpine"
    command: "npm run start:dev"
    env_file:
      - "server/.env.dev"
    volumes:
      - "./server:/app"
    ports:
      - "3001:3000"

  ui:
    container_name: "issues-dashboard-ui"
    working_dir: "/app"
    image: "node:12-alpine"
    command: "npm run start"
    stdin_open: true
    volumes:
      - "./ui:/app"
    ports:
      - "3000:3000"