version: "3"

networks:
  issue-board-test:

services:

  server:
    container_name: "issue-board-server-test"
    build:
      context: "./server"
      dockerfile: "Dockerfile.dev"
    command: "npm run test:e2e"
    env_file:
      - "server/.env.test"
    networks:
      - "issue-board-test"
    volumes:
      - "./server:/app"
      - "/app/node_modules"